config/routes.rb
Rails.application.routes.draw do
  root 'fitbit_auth#index'
  post "/auth/fitbit" => "fitbit_auth#make_request"
  get "/dashboard" => "fitbit_auth#dashboard"
  get "/auth/fitbit/callback" => "fitbit_auth#get_response"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/fitbit_auth_controller.rb
class FitbitAuthController < ApplicationController
 
  def index
    users = User.all
    @usernames = []
    users.each do |u|
      @usernames.push(u[:username])
    end
  end

  def dashboard
    users = User.all
    uids=[]
    users.each do |u|
      uids.push(u[:uid])
    end
    uid = uids[params[:index].to_i]
    @user = User.find_by(:uid => uid)
    @sleepChart = create_sleep_chart(uid)
    @activityChart = create_activity_chart(uid)
  end

  # this is the callback information from fitbit
  def get_response
    # Access Credentials
    oauth_token = params[:oauth_token]
    oauth_verifier = params[:oauth_verifier]

    # creates a variable we can pass as an argument below
    data = request.env['omniauth.auth']

    dates = ["2015-11-02", "2015-11-03", "2015-11-04", "2015-11-05", "2015-11-06"]
    dates.each do |d|
      get_user_activities(data, d)
    end
  end

private
  # this is the information we're sending to fitbit
  def get_user_activities(data, date)
    fitbit_user_id = data["uid"]

    user_secret = data["credentials"]["secret"]
    user_token = data["credentials"]["token"]

    
    # creates a new instance of Fitgem
    client = Fitgem::Client.new({
      consumer_key: '95ecbb851b8165022e445ff61c5248e5',
      consumer_secret: '58bafd75ecc502521569c8613d6ca33d',
      token: user_token,
      secret: user_secret,
      user_id: fitbit_user_id,
    })

    # Reconnects existing user using their credentials
    access_token = client.reconnect(user_token, user_secret)
    newuser = User.find_or_initialize_by(:uid => fitbit_user_id)
    profile = client.user_info()
    newuser.update_attributes(:username => profile["user"]["displayName"], :gender => profile["user"]["gender"], :dob => profile["user"]["dateOfBirth"] )
    
    record = Sleep.find_or_initialize_by(:uid => fitbit_user_id, :date => date)
    sleepinfo = client.sleep_on_date(date)
    unless sleepinfo["sleep"].nil?
      sleepinfo["sleep"].each do |s|
        if s["isMainSleep"] == true
          record.update_attributes(:minutesToFallAsleep => s["minutesToFallAsleep"], :awakeDuration => s["awakeDuration"], :awakeningsCount => s["awakeCount"], :totalMinutesAsleep => s["minutesAsleep"], :totalTimeInBed => s["timeInBed"], :startTime => s["startTime"])
        end
      end
    end

    act_record = Activity.find_or_initialize_by(:uid => fitbit_user_id, :date => date)
    activitiesinfo = client.activities_on_date(date)
    unless activitiesinfo["summary"].nil?
      act_record.update_attributes(:steps => activitiesinfo["summary"]["steps"], :failyActiveMinutes => activitiesinfo["summary"]["failyActiveMinutes"], :lightlyActiveMinutes => activitiesinfo["summary"]["lightlyActiveMinutes"], :sedentaryMinutes => activitiesinfo["summary"]["sedentaryMinutes"], :veryActiveMinutes => activitiesinfo["summary"]["veryActiveMinutes"])
    end
  end

  def create_sleep_chart(uid)
    sleeps = Sleep.where(:uid => uid)
    datetime = []
    awakeDurations = []
    awakeningsCounts = []
    minutesToFallAsleeps =[]
    totalMinutesAsleeps = []
    totalMinutesInBeds = []
    sleeps.each do |s|
      datetime.push(s[:date]+" "+s[:startTime][11..-5]+"AM")
      awakeDurations.push(s[:awakeDuration])
      awakeningsCounts.push(s[:awakeningsCounts])
      minutesToFallAsleeps.push(s[:minutesToFallAsleep])
      totalMinutesAsleeps.push(s[:totalMinutesAsleep])
      totalMinutesInBeds.push(s[:totalTimeInBed])
    end
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(:text => "Sleep summary")
      f.xAxis(:categories => datetime)
      f.series(:name => "minutes to fall asleep", :yAxis => 0, :data => minutesToFallAsleeps)
      f.series(:name => "awake times", :yAxis => 1, :data => awakeDurations)
      f.yAxis [
        {:title => {:text => "Minutes to Fall Asleep", :margin => 20} },
        {:title => {:text => "Awake Times"}, :opposite => true},
      ]

      f.legend(:align => 'center', :verticalAlign => 'bottom', :layout => 'horizontal',)
      f.chart({:defaultSeriesType=>"spline"})
    end
    return @chart    
  end

  def create_activity_chart(uid)
    activities = Activity.where(:uid => uid)
    dates = []
    steps = []
    sedentaryMinutes = []
    activities.each do |a|
      dates.push(a[:date])
      steps.push(a[:steps])
      sedentaryMinutes.push(a[:sedentaryMinutes])
    end
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(:text => "Activity summary")
      f.xAxis(:categories => dates)
      f.series(:name => "steps", :yAxis => 0, :data => steps)
      f.series(:name => "sedentary Minutes", :yAxis => 1, :data => sedentaryMinutes)
      f.yAxis [
        {:title => {:text => "Total steps", :margin => 20} },
        {:title => {:text => "Total sedentary minutes"}, :opposite => true},
      ]

      f.legend(:align => 'center', :verticalAlign => 'bottom', :layout => 'horizontal',)
      f.chart({:defaultSeriesType=>"column"})
    end
    return @chart    
  end
end

app/views/fitbit_auth/dashboard.html.erb
<!-- Find me in app/views/fitbit_auth/dashboard.html.erb -->
<div class="container">
	<div class="navbar-spacer"></div>
	<nav class="navbar">
		<div class="container">
			<ul class = "navbar-list">
				<li class="navbar-item"><a class="navbar-link" href="/"> <%= "< "+"Back" %></a></li>
				<li class="navbar-item"><a class="navbar-link" href="#intro">Intro</a></li>
				<li class="navbar-item"><a class="navbar-link" href="#sleep">Sleep</a></li>
				<li class="navbar-item"><a class="navbar-link" href="#activity">Activities</a></li>
			</ul>
		</div>
	</nav>

	<div class="docs-section" id="intro">
		<table class="u-full-width">
			<thead>
				<tr>
					<th>Name</th>
					<th>Gender</th>
					<th>Date of Birth</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><%= @user[:username] %></td>
					<td><%= @user[:gender] %></td>
					<td><%= @user[:dob] %></td>
				<tr>
			</tbody>
		</table>
	</div>

	<div class="docs-section" id="sleep">
		<%= high_chart("some_id", @sleepChart) %>
	</div>

	<div class="docs-section" id="activity">
		<%= high_chart("some_id_2", @activityChart) %>
	</div>
</div>

app/views/fitbit_auth/get_response.html.erb
<!-- Find me in app/views/fitbit_auth/get_response.html.erb -->
<div class="container">
	<div class="docs-section" id="intro">
		<h6 class="docs-header">Thank you!</h6>
		<%= link_to "Back", root_path %>
	</div>
</div>

app/views/fitbit_auth/index.html.erb
<!-- Find me in app/views/fitbit_auth/index.html.erb -->
<div class="container">
	<div class="eight columns">
		<div class="docs-section">
		<h6 class="docs-header">Getting started</h6>
			<p>Follow the instructions and authorize with your Fitbit account</p>
			<%= link_to "Connect with Fitbit", auth_fitbit_path, :class=>"button" %>
			<a class="button button-primary" href="#participants">Dashboard</a>
		</div>
	</div>
</div>

<div class="container">
	<div class="docs-section" id="participants">
		<h6 class="docs-header">Partcipants</h6>
		<table>
			<tbody>
				<% @usernames.each_with_index do |u, index| %>
				<th>
					<span>
						<%= link_to "#{u[0]}", {:controller => "fitbit_auth", :action => "dashboard", :index => index} %>
					</span>
				</th>
				<% end %>	
			</tbody>
		</table>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Health Tech Lab3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
  <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
</head>
<body>
<%= yield %>

</body>
</html>